CREATE TYPE SQL_DETAIL_TYPE AS OBJECT
(SQL_ID VARCHAR2(13),
 PLAN_HASH_VALUE NUMBER,
 OBJECT#  NUMBER,
 OBJECT_OWNER VARCHAR2(128),
 OBJECT_NAME VARCHAR2(128),
 OBJECT_ALIAS VARCHAR2(261),
 OBJECT_TYPE VARCHAR2(60),
 OPTIONS VARCHAR2(120)) ;
/ 
