CREATE TABLE MSM_TOP_SQL
(
 DBNAME VARCHAR2(9),
 HOST_NAME VARCHAR2(64),
 SQL_ID VARCHAR2(13),
 EXEC_PCT NUMBER(5,2),
 BUF_PCT NUMBER(5,2),
 CPU_PCT NUMBER(5,2),
 ELP_PCT NUMBER(5,2),
 SQL_TEXT VARCHAR2(110),
 CREATED_TIME DATE DEFAULT SYSDATE,
 LAST_UPDATE_TIME DATE
);

CREATE UNIQUE INDEX MSM_TOP_SQL_UK ON MSM_TOP_SQL (DBNAME,HOST_NAME,SQL_ID) ;

GRANT SELECT ON  SQLMON.MSM_TOP_SQL TO PUBLIC ;
CREATE PUBLIC SYNONYM MSM_TOP_SQL FOR SQLMON.MSM_TOP_SQL;

